//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int id { get; set; }
        public string imglogo { get; set; }
        public string nameLogo { get; set; }
        public string groupLogo { get; set; }
        public string slideI1img1 { get; set; }
        public string slideI1img2 { get; set; }
        public string slide1Title { get; set; }
        public string slide2Title { get; set; }
        public string slide1Desc { get; set; }
        public string slide2Desc { get; set; }
        public string main1Title { get; set; }
        public string main2Title { get; set; }
        public string main1Desc { get; set; }
        public string main2Desc { get; set; }
        public string main1Img { get; set; }
        public string main2Img { get; set; }
        public string product1Title { get; set; }
        public string product2Title { get; set; }
        public string product3Title { get; set; }
        public string product1Desc { get; set; }
        public string product2Desc { get; set; }
        public string product3Desc { get; set; }
        public string product1Img { get; set; }
        public string product2Img { get; set; }
        public string product3Img { get; set; }
        public string crop1Title { get; set; }
        public string crop2Title { get; set; }
        public string crop1address { get; set; }
        public string crop2address { get; set; }
        public string crop1Img { get; set; }
        public string crop2Img { get; set; }
        public string crop1Desc { get; set; }
        public string crop2Desc { get; set; }
        public string FooterDesc { get; set; }
        public string address { get; set; }
        public string gmail { get; set; }
        public string phone { get; set; }
    }
}
